import mongoose from 'mongoose';

// Sub-schema for granular tracking of exactly what user activity happened and when
const statusHistorySchema = new mongoose.Schema({
  status: {
    type: String,
    required: true,
    enum: [
      'Pending',
      'Shipment Created',
      'Label Purchased',
      'Packing Slip Downloaded',
      'Voided',
      'Label Voided',
      'Shipment Cancelled'
    ]
  },
  notes: {
    type: String, // e.g., "Label generated by John Doe", "Packing slip printed"
  },
  timestamp: {
    type: Date,
    default: Date.now
  }
});

const shipmentSchema = new mongoose.Schema({
  order: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Order',
    required: true,
    unique: true // 🚨 CRITICAL: Prevents creating multiple shipments/activity logs for one order
  },
  division: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Division',
    required: true
  },
  
  // --- Fulfillment Activity Flags ---
  isShipmentCreated: {
    type: Boolean,
    default: false
  },
  isLabelPurchased: {
    type: Boolean,
    default: false
  },
  isPackingSlipDownloaded: {
    type: Boolean,
    default: false
  },

  // --- External API Identifiers ---
  // We keep these so we know exactly which ShipStation object this log refers to
  shipStationShipmentId: {
    type: String, 
  },
  shipStationLabelId: {
    type: String, 
  },

  // --- State & History ---
  currentStatus: {
    type: String,
    default: 'Pending',
    enum: [
      'Pending',
      'Shipment Created',
      'Label Purchased',
      'Packing Slip Downloaded',
      'Voided',
      'Label Voided',
      'Shipment Cancelled'
    ]
  },
  statusHistory: [statusHistorySchema]

}, { 
  timestamps: true 
});

// Middleware: Automatically push the initial status into the history array upon creation
shipmentSchema.pre('save', function() {
  if (this.isNew && this.statusHistory.length === 0) {
    this.statusHistory.push({
      status: this.currentStatus,
      notes: 'Fulfillment tracking initialized.'
    });
  }
});

export default mongoose.model('Shipment', shipmentSchema);