name: deploy cobra backend
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cobra-backend .
      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cobra-backend:latest

  deploy: 
    needs: build
    runs-on: self-hosted
    steps:
        - name: Pull Docker image from DockerHub
          run: docker pull ${{ secrets.DOCKER_USERNAME }}/cobra-backend:latest
        - name: RUN Docker container
          run: docker run -d -p 5000:5000 --name cobra-backend-container ${{ secrets.DOCKER_USERNAME }}/cobra-backend:latest