name: deploy cobra backend

on:
  push:
    branches:
      - main
    paths:
      - 'backends/**' # Only triggers when the backend code changes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cobra-backend:latest

  deploy: 
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker image from DockerHub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/cobra-backend:latest

      - name: Stop and remove old container
        run: |
          docker stop cobra-backend-container || true
          docker rm -f cobra-backend-container || true

      - name: Create .env file dynamically on AWS
        run: |
          cat << EOF > .env
          NODE_ENV=production
          PORT=5000
          MONGO_URI=$MONGO_URI
          JWT_SECRET=$JWT_SECRET
          JWT_EXPIRES_IN=30d
          AWS_REGION=us-east-1
          AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          AWS_S3_BUCKET_NAME=cobra-2-assets
          SHIPSTATION_API_KEY=$SHIPSTATION_API_KEY
          SHIPSTATION_API_URL=https://api.shipstation.com/v2
          SHIPSTATION_ORIGIN_ZIP=08036
          SMTP_HOST=$SMTP_HOST
          SMTP_PORT=$SMTP_PORT
          SMTP_USER=$SMTP_USER
          SMTP_PASS=$SMTP_PASS
          FROM_EMAIL=$FROM_EMAIL
          EOF
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SHIPSTATION_API_KEY: ${{ secrets.SHIPSTATION_API_KEY }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}

      - name: RUN Docker container with env file
        run: |
          docker run -d \
            -p 5000:5000 \
            --name cobra-backend-container \
            --restart unless-stopped \
            --env-file .env \
            ${{ secrets.DOCKER_USERNAME }}/cobra-backend:latest

      - name: Clean up secrets
        if: always()
        run: rm -f .env